-- AlterTable
ALTER TABLE "Autenticacion" ALTER COLUMN "fecha_creacion" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Plan" ALTER COLUMN "fecha" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Sugerencia" ALTER COLUMN "fecha" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Usuario" ALTER COLUMN "fecha_creacion" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "id_rol" SET DEFAULT 1;
